### ISSUE TITLE
No such file or directory: 'content.md'

### ISSUE THREAD

**Issue by YannickXiong** [satwikkansal/wtfpython#119]
# OS / Environment
macOS mojave 10.14.1

# Manticore version
Version: 0.2

# Python version
python 3.6

# Dependencies

# Summary of the problem

install wtfpython with `pip install wtfpython` successfully, however run the commond line failed, the error log is:

```
 ~  wtfpython
Fetching the latest version...
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
Uh oh, failed to check for the latest version, using the local version for now.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/wtfpython", line 10, in <module>
    sys.exit(load_and_read())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wtf_python/main.py", line 31, in load_and_read
    render_doc()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wtf_python/main.py", line 24, in render_doc
    with open(file_name, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'content.md'
```

**Comment by satwikkansal** [comment]
@YannickXiong thanks for reporting this, I'm looking into it. Will let you know once this is fixed.

**Comment by satwikkansal** [comment]
This will be fixed with https://github.com/satwikkansal/wtfpython/commit/c475cbfe826f2b65d3674f3acf724f14f97c50dc

Thanks for reporting!
