### ISSUE TITLE
Another mangling example

### ISSUE THREAD

**Issue by MatzeB** [satwikkansal/wtfpython#202]
```
>>> def __greet():
...   print("hello")
...
>>> __greet()
hello
>>> class C:
...   def run(self):
...     __greet()
...
>>> C().run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in run
NameError: name '_C__greet' is not defined
```

**Comment by satwikkansal** [comment]
Interesting, I'm wondering what should be the right way to call `__greet` inside the `run` method then
