### ISSUE TITLE
Weird variable scope in functions

### ISSUE THREAD

**Issue by dan-t** [satwikkansal/wtfpython#248]
>>> def foo(x):
...    if x:
...       y = 1
...    print(f"y={y}")
... 
>>> foo(1)
y=1
>>> foo(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in foo
UnboundLocalError: local variable 'y' referenced before assignment

**Comment by dan-t** [comment]
And now with sensible formating ...

``` python
def foo(x):
    if x:
        y = 1
    print(f"y={y}")

foo(1)
y=1

foo(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in foo
UnboundLocalError: local variable 'y' referenced before assignment
```
